# Generated by Django 5.2.4 on 2025-10-16 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_remove_taskdetail_assigned_to"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskdetail",
            name="assigned_to",
            field=models.CharField(default=1, max_length=100),
        ),
    ]
