# Generated by Django 5.2.4 on 2025-11-27 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0004_alter_taskdetail_task"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="is_completed",
        ),
    ]
