# Generated by Django 5.2.4 on 2025-11-28 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0005_remove_task_is_completed"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="assigned_to",
        ),
    ]
