# Generated by Django 5.2.4 on 2025-11-29 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0007_task_assigned_to"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Employee",
        ),
    ]
