# Generated by Django 5.2.4 on 2025-11-30 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0008_delete_employee"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="taskdetail",
            name="assigned_to",
        ),
    ]
