# Generated by Django 5.2.4 on 2025-11-30 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0009_remove_taskdetail_assigned_to"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskdetail",
            name="asset",
            field=models.ImageField(blank=True, null=True, upload_to="tasks_asset"),
        ),
    ]
